### ISSUE TITLE
Update to new Extra Life Logo

### ISSUE THREAD

**Issue by cherrypibb** [weegeekps/extra-life-overlay#14]
Can you update the image to the new logo? It is available in the icon pack on the extra life site.

**Comment by weegeekps** [comment]
@cherrypibb Just an FYI, this is now done. You can also choose between the "Wings" Controller logo or the Dice logo this year. If you're good with just the "Wings" controller logo, you don´t have to set anything, but add `&logo=dice2021` to the end of your URL if you´d like to use the dice logo.
